config/routes.rb
Rails.application.routes.draw do
  resources :project_statuses
  root to: 'projects#index'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get "/logout" => 'sessions#destroy'
  get '/login' => 'login#index'
  post '/crear-carpeta' => 'project_folders#add_folder'

  scope(:path_names => { :new => "nuevo", :edit => "editar", :create => "crear", :delete => "eliminar" }) do
    resources :project_files, :path=>'archivos'
    resources :project_participants, :path => 'participantes'
    resources :projects, :path => "proyectos"  do
      member do

        get :details, :path => "detalles"

        get :messages, :path => "mensajes"
        get :new_message, :path => "mensajes/nuevo"
        get :show_message, :path => "mensajes/:message_id"
        get :edit_message, :path => "mensajes/:message_id/editar"

        get :schedules, :path => "calendario"
        get :new_schedule, :path => "calendario/nuevo"
        get :show_schedule, :path => "calendario/:schedule_id"
        get :edit_schedule, :path => "calendario/:schedule_id/editar"

        get :files, :path => "documentos"
        get :folders, :path => "documentos/carpetas"
        get :folder_files, :path => "documentos/:project_folder_id"
        get :folder_files_list, :path => "documentos/:project_folder_id/listado"


        get :budget, :path => "presupuesto"
        get :budget_details, :path => "presupuesto/detalle"
        get :purchase_requests, :path => "presupuesto/requisiciones"
        get :show_purchase_request, :path => "presupuesto/requisiciones/:req_id"

        get :people, :path => "personas"

        get :services, :path => "servicios"

        patch :update_status, :path => "update-status"
      end
    end   
  end

  get '/configuracion' => 'admin#index'

  scope '/configuracion' do
    scope(:path_names => { :new => "nuevo", :edit => "editar" }) do
      resources :users, :path => "usuarios"   
      resources :project_types, :path => "tipos-de-proyectos"  do
        member do
          post "reorder-status"
          post "add-status"
          post "add-folder"
          post "update-status"
          get  "statuses"
        end
      end
      resources :industries, :path => "industrias"   
      resources :company_sizes, :path => "company_sizes"   
      resources :departments, :path => "departamentos"   
      resources :clients, :path => "clientes"   
    end 
  end



  resources :business_units
  resources :schedules
  resources :messages
  resources :departments
  resources :project_folders
  
  resources :industries
  resources :people
  resources :institutions
  resources :company_sizes
  resources :clients
  resources :themes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/controllers/project_statuses_controller.rb
class ProjectStatusesController < ApplicationController
  before_action :set_project_status, only: [:show, :edit, :update, :destroy]

  # GET /project_statuses
  # GET /project_statuses.json
  def index
    @project_statuses = ProjectStatus.all
  end

  # GET /project_statuses/1
  # GET /project_statuses/1.json
  def show
  end

  # GET /project_statuses/new
  def new
    @project_status = ProjectStatus.new
  end

  # GET /project_statuses/1/edit
  def edit
  end

  # POST /project_statuses
  # POST /project_statuses.json
  def create
    @project_status = ProjectStatus.new(project_status_params)

    respond_to do |format|
      if @project_status.save
        format.html { redirect_to @project_status, notice: 'Project status was successfully created.' }
        format.json { render :show, status: :created, location: @project_status }
      else
        format.html { render :new }
        format.json { render json: @project_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /project_statuses/1
  # PATCH/PUT /project_statuses/1.json
  def update
    respond_to do |format|
      if @project_status.update(project_status_params)
        format.html { redirect_to @project_status, notice: 'Project status was successfully updated.' }
        format.json { render :show, status: :ok, location: @project_status }
      else
        format.html { render :edit }
        format.json { render json: @project_status.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /project_statuses/1
  # DELETE /project_statuses/1.json
  def destroy
    @project_status.destroy
    respond_to do |format|
      format.html { redirect_to project_statuses_url, notice: 'Project status was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_project_status
      @project_status = ProjectStatus.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def project_status_params
      params.require(:project_status).permit(:name, :position, :project_type_id)
    end
end

app/helpers/project_statuses_helper.rb
module ProjectStatusesHelper
end

app/views/project_statuses/_form.html.erb
<%= form_with(model: project_status, local: true) do |form| %>
  <% if project_status.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(project_status.errors.count, "error") %> prohibited this project_status from being saved:</h2>

      <ul>
      <% project_status.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :name %>
    <%= form.text_field :name, id: :project_status_name %>
  </div>

  <div class="field">
    <%= form.label :position %>
    <%= form.number_field :position, id: :project_status_position %>
  </div>

  <div class="field">
    <%= form.label :project_type_id %>
    <%= form.text_field :project_type_id, id: :project_status_project_type_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/project_statuses/edit.html.erb
<h1>Editing Project Status</h1>

<%= render 'form', project_status: @project_status %>

<%= link_to 'Show', @project_status %> |
<%= link_to 'Back', project_statuses_path %>

app/views/project_statuses/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Project Statuses</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th>Position</th>
      <th>Project type</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @project_statuses.each do |project_status| %>
      <tr>
        <td><%= project_status.name %></td>
        <td><%= project_status.position %></td>
        <td><%= project_status.project_type %></td>
        <td><%= link_to 'Show', project_status %></td>
        <td><%= link_to 'Edit', edit_project_status_path(project_status) %></td>
        <td><%= link_to 'Destroy', project_status, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Project Status', new_project_status_path %>

app/views/project_statuses/new.html.erb
<h1>New Project Status</h1>

<%= render 'form', project_status: @project_status %>

<%= link_to 'Back', project_statuses_path %>

app/views/project_statuses/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @project_status.name %>
</p>

<p>
  <strong>Position:</strong>
  <%= @project_status.position %>
</p>

<p>
  <strong>Project type:</strong>
  <%= @project_status.project_type %>
</p>

<%= link_to 'Edit', edit_project_status_path(@project_status) %> |
<%= link_to 'Back', project_statuses_path %>