config/routes.rb
Rails.application.routes.draw do
  resources :project_statuses
  root to: 'projects#index'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get "/logout" => 'sessions#destroy'
  get '/login' => 'login#index'
  post '/crear-carpeta' => 'project_folders#add_folder'

  scope(:path_names => { :new => "nuevo", :edit => "editar", :create => "crear", :delete => "eliminar" }) do
    resources :project_files, :path=>'archivos'
    resources :project_participants, :path => 'participantes'
    resources :projects, :path => "proyectos"  do
      member do

        get :details, :path => "detalles"

        get :messages, :path => "mensajes"
        get :new_message, :path => "mensajes/nuevo"
        get :show_message, :path => "mensajes/:message_id"
        get :edit_message, :path => "mensajes/:message_id/editar"

        get :schedules, :path => "calendario"
        get :new_schedule, :path => "calendario/nuevo"
        get :show_schedule, :path => "calendario/:schedule_id"
        get :edit_schedule, :path => "calendario/:schedule_id/editar"

        get :files, :path => "documentos"
        get :folders, :path => "documentos/carpetas"
        get :folder_files, :path => "documentos/:project_folder_id"
        get :folder_files_list, :path => "documentos/:project_folder_id/listado"


        get :budget, :path => "presupuesto"
        get :budget_details, :path => "presupuesto/detalle"
        get :purchase_requests, :path => "presupuesto/requisiciones"
        get :show_purchase_request, :path => "presupuesto/requisiciones/:req_id"

        get :people, :path => "personas"

        get :services, :path => "servicios"

        patch :update_status, :path => "update-status"
      end
    end   
  end

  get '/configuracion' => 'admin#index'

  scope '/configuracion' do
    scope(:path_names => { :new => "nuevo", :edit => "editar" }) do
      resources :users, :path => "usuarios"   
      resources :project_types, :path => "tipos-de-proyectos"  do
        member do
          post "reorder-status"
          post "add-status"
          post "add-folder"
          post "update-status"
          get  "statuses"
        end
      end
      resources :industries, :path => "industrias"   
      resources :company_sizes, :path => "company_sizes"   
      resources :departments, :path => "departamentos"   
      resources :clients, :path => "clientes"   
    end 
  end



  resources :business_units
  resources :schedules
  resources :messages
  resources :departments
  resources :project_folders
  
  resources :industries
  resources :people
  resources :institutions
  resources :company_sizes
  resources :clients
  resources :themes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/schedule.rb
class Schedule < ApplicationRecord
  belongs_to :project
  belongs_to :user

  DATE = 1
  PROJECT_DURATION = 99

  TYPE_TEXT = {
    DATE => "Fecha importante",
    PROJECT_DURATION   => "Duración del proyecto",
  }

  ACTIVE = 1
  DELETED = 2

  def type_text
    TYPE_TEXT[schedule_type.to_i]
  end
end

app/controllers/schedules_controller.rb
class SchedulesController < ApplicationController
  before_action :set_schedule, only: [:show, :edit, :update, :destroy]

  # GET /schedules
  # GET /schedules.json
  def index
    @schedules = Schedule.all
  end

  # GET /schedules/1
  # GET /schedules/1.json
  def show
  end

  # GET /schedules/new
  def new
    @schedule = Schedule.new
  end

  # GET /schedules/1/edit
  def edit
  end

  # POST /schedules
  # POST /schedules.json
  def create
    @schedule = Schedule.new(schedule_params)
    @schedule.user_id = current_user.id
    @schedule.status = Schedule::ACTIVE
    @schedule.schedule_type = Schedule::DATE
    @project = @schedule.project

    if (params[:all_day]) 
      start_date = params[:start_date_date].to_s +  ' 00:00:00'
      end_date = params[:end_date_date].to_s +  ' 00:00:00'
    else
      start_date = params[:start_date_date].to_s +  ' ' + params['start_date_hours']
      end_date = params[:end_date_date].to_s +  ' ' + params['end_date_hours']
    end

    @schedule.start_date = start_date
    @schedule.end_date = end_date

    respond_to do |format|
      if @schedule.save
        format.html { redirect_to schedules_project_url(@project), notice: 'Evento agregado.' }
        format.json { render :show, status: :created, location: @schedule }
      else
        format.html { render "projects/new_schedule", schedule: @schedule, project: @project, notice: 'No se pudo agregar.'}
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end


  # PATCH/PUT /schedules/1
  # PATCH/PUT /schedules/1.json
  def update
    @project = @schedule.project

    if (params[:all_day]) 
      start_date = params[:start_date_date].to_s +  ' 00:00:00'
      end_date = params[:end_date_date].to_s +  ' 00:00:00'
    else
      start_date = params[:start_date_date].to_s +  ' ' + params['start_date_hours']
      end_date = params[:end_date_date].to_s +  ' ' + params['end_date_hours']
    end

    @schedule.start_date = start_date
    @schedule.end_date = end_date
    
    respond_to do |format|
      if @schedule.update(schedule_params)
        format.html { redirect_to schedules_project_url(@project), notice: 'Evento actualizado.' }
        format.json { render :show, status: :ok, location: @schedule }
      else
        format.html { render "projects/edit_schedule", schedule: @schedule, project: @project, notice: 'No se pudo actualizar.'}
        format.json { render json: @schedule.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /schedules/1
  # DELETE /schedules/1.json
  def destroy
    @schedule.destroy
    respond_to do |format|
      format.html { redirect_to schedules_url, notice: 'Schedule was successfully destroyed.' }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_schedule
      @schedule = Schedule.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def schedule_params
      puts params
      params.require(:schedule).permit(:title, :content, :project_id, :all_day, :start_date_date, :start_date_hours, :end_date_date, :end_date_hours, :schedule_type, :user_id)
    end
end

app/helpers/schedules_helper.rb
module SchedulesHelper
end

app/views/schedules/_form.html.erb
<%= form_with(model: schedule, local: true) do |form| %>
  <% if schedule.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(schedule.errors.count, "error") %> prohibited this schedule from being saved:</h2>

      <ul>
      <% schedule.errors.full_messages.each do |message| %>
        <li><%= message %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :title %>
    <%= form.text_field :title, id: :schedule_title %>
  </div>

  <div class="field">
    <%= form.label :content %>
    <%= form.text_area :content, id: :schedule_content %>
  </div>

  <div class="field">
    <%= form.label :project_id %>
    <%= form.text_field :project_id, id: :schedule_project_id %>
  </div>

  <div class="field">
    <%= form.label :start_date %>
    <%= form.datetime_select :start_date, id: :schedule_start_date %>
  </div>

  <div class="field">
    <%= form.label :end_date %>
    <%= form.datetime_select :end_date, id: :schedule_end_date %>
  </div>

  <div class="field">
    <%= form.label :schedule_type %>
    <%= form.number_field :schedule_type, id: :schedule_schedule_type %>
  </div>

  <div class="field">
    <%= form.label :user_id %>
    <%= form.text_field :user_id, id: :schedule_user_id %>
  </div>

  <div class="actions">
    <%= form.submit %>
  </div>
<% end %>

app/views/schedules/edit.html.erb
<h1>Editing Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Show', @schedule %> |
<%= link_to 'Back', schedules_path %>

app/views/schedules/index.html.erb
<p id="notice"><%= notice %></p>

<h1>Schedules</h1>

<table>
  <thead>
    <tr>
      <th>Title</th>
      <th>Content</th>
      <th>Project</th>
      <th>Start date</th>
      <th>End date</th>
      <th>Schedule type</th>
      <th>User</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% @schedules.each do |schedule| %>
      <tr>
        <td><%= schedule.title %></td>
        <td><%= schedule.content %></td>
        <td><%= schedule.project %></td>
        <td><%= schedule.start_date %></td>
        <td><%= schedule.end_date %></td>
        <td><%= schedule.schedule_type %></td>
        <td><%= schedule.user %></td>
        <td><%= link_to 'Show', schedule %></td>
        <td><%= link_to 'Edit', edit_schedule_path(schedule) %></td>
        <td><%= link_to 'Destroy', schedule, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Schedule', new_schedule_path %>

app/views/schedules/new.html.erb
<h1>New Schedule</h1>

<%= render 'form', schedule: @schedule %>

<%= link_to 'Back', schedules_path %>

app/views/schedules/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Title:</strong>
  <%= @schedule.title %>
</p>

<p>
  <strong>Content:</strong>
  <%= @schedule.content %>
</p>

<p>
  <strong>Project:</strong>
  <%= @schedule.project %>
</p>

<p>
  <strong>Start date:</strong>
  <%= @schedule.start_date %>
</p>

<p>
  <strong>End date:</strong>
  <%= @schedule.end_date %>
</p>

<p>
  <strong>Schedule type:</strong>
  <%= @schedule.schedule_type %>
</p>

<p>
  <strong>User:</strong>
  <%= @schedule.user %>
</p>

<%= link_to 'Edit', edit_schedule_path(@schedule) %> |
<%= link_to 'Back', schedules_path %>