config/routes.rb
Rails.application.routes.draw do
  resources :project_statuses
  root to: 'projects#index'

  get '/auth/:provider/callback' => 'sessions#create'
  get '/auth/failure' => 'sessions#failure'
  get "/logout" => 'sessions#destroy'
  get '/login' => 'login#index'
  post '/crear-carpeta' => 'project_folders#add_folder'

  scope(:path_names => { :new => "nuevo", :edit => "editar", :create => "crear", :delete => "eliminar" }) do
    resources :project_files, :path=>'archivos'
    resources :project_participants, :path => 'participantes'
    resources :projects, :path => "proyectos"  do
      member do

        get :details, :path => "detalles"

        get :messages, :path => "mensajes"
        get :new_message, :path => "mensajes/nuevo"
        get :show_message, :path => "mensajes/:message_id"
        get :edit_message, :path => "mensajes/:message_id/editar"

        get :schedules, :path => "calendario"
        get :new_schedule, :path => "calendario/nuevo"
        get :show_schedule, :path => "calendario/:schedule_id"
        get :edit_schedule, :path => "calendario/:schedule_id/editar"

        get :files, :path => "documentos"
        get :folders, :path => "documentos/carpetas"
        get :folder_files, :path => "documentos/:project_folder_id"
        get :folder_files_list, :path => "documentos/:project_folder_id/listado"


        get :budget, :path => "presupuesto"
        get :budget_details, :path => "presupuesto/detalle"
        get :purchase_requests, :path => "presupuesto/requisiciones"
        get :show_purchase_request, :path => "presupuesto/requisiciones/:req_id"

        get :people, :path => "personas"

        get :services, :path => "servicios"

        patch :update_status, :path => "update-status"
      end
    end   
  end

  get '/configuracion' => 'admin#index'

  scope '/configuracion' do
    scope(:path_names => { :new => "nuevo", :edit => "editar" }) do
      resources :users, :path => "usuarios"   
      resources :project_types, :path => "tipos-de-proyectos"  do
        member do
          post "reorder-status"
          post "add-status"
          post "add-folder"
          post "update-status"
          get  "statuses"
        end
      end
      resources :industries, :path => "industrias"   
      resources :company_sizes, :path => "company_sizes"   
      resources :departments, :path => "departamentos"   
      resources :clients, :path => "clientes"   
    end 
  end



  resources :business_units
  resources :schedules
  resources :messages
  resources :departments
  resources :project_folders
  
  resources :industries
  resources :people
  resources :institutions
  resources :company_sizes
  resources :clients
  resources :themes
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/models/project_type.rb
class ProjectType < ApplicationRecord
  has_many :projects
  has_many :project_statuses
end

app/controllers/projects_controller.rb
class ProjectsController < ApplicationController
  before_action :auth_required
  before_action :set_project, only: [:show, :edit, :update, :destroy, :messages, 
                                     :new_message, :show_message, :edit_message, 
                                     :schedules, :new_schedule, :show_schedule, 
                                     :edit_schedule, :files, :folder_files, 
                                     :folder_files_list, :folders, :budget, 
                                     :budget_details, :purchase_requests, 
                                     :show_purchase_request, :people, :services,
                                     :details, :update_status ]

  # GET /projects
  # GET /projects.json
  def index
    @p = params[:p]
    @p = 'mis-proyectos' if !@p

    case @p 
    when 'responsable'
      @projects = Project.where("manager_id = ? AND status <> ? AND status <> ?", current_user.id, Project::STATUS_END, Project::STATUS_CANCELLED)
    when 'participo'
      @projects = Project.where("(manager_id = ? OR agent_id = ? OR ? IN (SELECT user_id FROM project_participants WHERE project_id = projects.id) ) AND (status <> ? AND status <> ?)", current_user.id, current_user.id, current_user.id, Project::STATUS_END, Project::STATUS_CANCELLED)
    when 'mis-proyectos'
      @projects = Project.where("manager_id = ? OR agent_id = ? OR ? IN (SELECT user_id FROM project_participants WHERE project_id = projects.id)", current_user.id, current_user.id, current_user.id)
    when 'administro'
      @projects = Project.where("agent_id = ? AND status <> ? AND status <> ?", current_user.id, Project::STATUS_END, Project::STATUS_CANCELLED)
    when 'activos'
      @projects = Project.all
    when 'todos'
      @projects = Project.all
    end 
    
  end

  # GET /projects/1
  # GET /projects/1.json
  def show
  end

  def details
  end

  # GET /projects/new
  def new
    @project = Project.new
  end

  # GET /projects/1/edit
  def edit
  end

  # POST /projects
  # POST /projects.json
  def create
    @project = Project.new(project_params)

    @project.agent_id = current_user.id
    @project.business_unit_id = current_user.business_unit_id

    respond_to do |format|
      if @project.save
        format.html { redirect_to @project, notice: 'Proyecto creado.' }
        format.json { render :show, status: :created, location: @project }
      else
        format.html { render :new }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /projects/1
  # PATCH/PUT /projects/1.json
  def update
    respond_to do |format|
      if @project.update(project_params)
  
        #UPDATE dates
        pd_res = @project.schedules.where(schedule_type: Schedule::PROJECT_DURATION)
        if pd_res.count == 1
          project_duration = pd_res.first
          project_duration.user_id = current_user.id
        else
          project_duration = @project.schedules.new
          project_duration.title = "Duración del proyecto"
          project_duration.content = ""
          project_duration.user_id = current_user.id
          project_duration.schedule_type = Schedule::PROJECT_DURATION
          project_duration.status = Schedule::ACTIVE
        end
        project_duration.start_date = params[:project_start_date]
        project_duration.end_date = params[:project_end_date]
        project_duration.save

        format.html { redirect_to details_project_url, notice: 'Proyecto actualizado.' }
        format.json { render :details, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  def update_status
    prev_status = @project.project_status.name

    @project.status = params[:new_status]

    respond_to do |format|
      if @project.save
        
        nm = @project.messages.new
        nm.user_id = current_user.id
        nm.title = "Proyecto #{@project.number} cambió a #{@project.project_status.name}"
        nm.content = "Proyecto #{@project.number} cambió de #{prev_status} a #{@project.project_status.name}.<br/>#{params['status_notes']}"
        nm.status = Message::ACTIVE
        nm.message_type = Message::TYPE_STATUS
        nm.save

        format.html { redirect_to details_project_url, notice: 'Estado actualizado.' }
        format.json { render :details, status: :ok, location: @project }
      else
        format.html { render :edit }
        format.json { render json: @project.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /projects/1
  # DELETE /projects/1.json
  def destroy
    @project.destroy
    respond_to do |format|
      format.html { redirect_to projects_url, notice: 'Proyecto eliminado.' }
      format.json { head :no_content }
    end
  end

  def messages
    
  end

  def new_message
    @message = @project.messages.new
  end

  def show_message
    @message = @project.messages.find(params[:message_id])
  end

  def edit_message
    @message = @project.messages.find(params[:message_id])
  end  

  def schedules
  end

  def new_schedule
    @schedule = @project.schedules.new
  end

  def show_schedule
    @schedule = @project.schedules.find(params[:schedule_id])
  end

  def edit_schedule
    @schedule = @project.schedules.find(params[:schedule_id])
  end  

  def files
    # Redirect to first folder
    first = @project.project_folders.order(:name).first 
    

    redirect_to action: "folder_files", id: @project.id, project_folder_id: first.id
  end

  def folder_files
    if params[:project_folder_id] && params[:project_folder_id].to_i > 0
      @project_folder = @project.project_folders.find(params[:project_folder_id]) 
    end
  end

  def folder_files_list
    @project_folder = @project.project_folders.find(params[:project_folder_id]) 
    render layout: false
  end

  def folders
    render layout: false
  end

  def add_folder
    folder = @project.project_folders.new
    folder.name = params[:new_folder]
    folder.user_id = 72
    respond_to do |format|
      if folder.save
        format.html do
          if request.xhr?
            json = {}
            json[:new_status_id] = folder.id
            json[:flash] = 'Nueva carpeta guardada'
            render :json => json
          else
            redirect_to @project_type
          end
        end
      else
        format.html do
          if request.xhr?
            json = {}
            json[:flash] = 'Error al guardar'
            json[:errors] = folder.errors
            render :json => json, :status => :unprocessable_entity
          else
            redirect_to @project_type
          end
        end
      end
    end
  end

  def budget

  end

  def budget_details

  end

  def purchase_requests 
  end

  def show_purchase_request
    sql = "SELECT 
             co01_requisicion AS requisicion, 
             concat(SUBSTRING(co01_fecha_req,7,2),'/',SUBSTRING(co01_fecha_req,5,2),'/',SUBSTRING(co01_fecha_req,1,4)) AS fecha, 
             co01_cve_responsable, 
             CONCAT(TRIM(r.no01_nombre),' ',TRIM(r.no01_apellido_pat),' ',TRIM(r.no01_apellido_mat)) AS responsable, 
             co01_usuario, 
             CONCAT(TRIM(u.no01_nombre),' ',TRIM(u.no01_apellido_pat),' ',TRIM(u.no01_apellido_mat)) AS usuario, 
             co01_solicitante, 
             CONCAT(TRIM(s.no01_nombre),' ',TRIM(s.no01_apellido_pat),' ',TRIM(s.no01_apellido_mat)) AS solicitante, 
             co01_status AS status, 
             co02_proyecto AS cproyecto, 
             pr10_desc_completa AS proyecto, 
             co02_sol_cotizacion AS cotizacion,
             co02_partida AS partida, 
             co02_descripcion AS descripcion, 
             co02_desc_larga AS desclarga, 
             co02_status AS status2, 
             pv01_nombre AS proveedor,
             co03_tiempo_entrega AS tiempoentrega,
             co09_cant_rec AS cantidad, 
             co09_costo AS costo, 
             co09_importe_ped AS importe, 
             co09_importe_iva AS iva, 
             co09_impuesto AS impuesto, 
             co18_desc_sesion AS sesion, 
             co05_pedido AS ordencompra, 
             CONCAT(SUBSTRING(co05_fecha_pedido,7,2),'/',SUBSTRING(co05_fecha_pedido,5,2),'/',SUBSTRING(co05_fecha_pedido,1,4)) AS fechaordencompra,
             CONCAT(SUBSTRING(co02_fecha_sesion,7,2),'/',SUBSTRING(co02_fecha_sesion,5,2),'/',SUBSTRING(co02_fecha_sesion,1,4)) AS fechasesion 
           FROM 
             netmultix.co01 
             INNER JOIN netmultix.co02 on co01_requisicion = co02_requisicion 
             LEFT JOIN netmultix.co09 on co01_requisicion = co09_requisicion and co02_id = co09_id 
             LEFT JOIN netmultix.co05 on co05_sol_cotizacion = co02_sol_cotizacion 
             LEFT JOIN netmultix.co03 on co03_sol_cotizacion = co02_sol_cotizacion and co03_cve_prov = co05_cve_prov 
             LEFT JOIN netmultix.pv01 on co03_cve_prov = pv01_clave 
             LEFT JOIN netmultix.pr10 on co02_proyecto = pr10_proyecto 
             LEFT JOIN netmultix.co18 on co02_sesion = co18_id_sesion 
             LEFT JOIN netmultix.no01 u on co01_usuario = u.no01_cve_emp 
             LEFT JOIN netmultix.no01 r on co01_cve_responsable = r.no01_cve_emp 
             LEFT JOIN netmultix.no01 s on co01_solicitante = s.no01_cve_emp 
          WHERE CO01_REQUISICION = '#{params[:req_id]}'"

    @request = {} 
    connection = ActiveRecord::Base.connection
    result = connection.exec_query(sql)


    @request['number'] = params[:req_id]
    @request['details'] = []
    
    result.each do |row|
      row['estado'] = Project::STATUS_REQ_TEXT[row['status'].to_i]
      @request['details'] << row
    end

    sql_comments = "SELECT * FROM netmultix.pr07h WHERE pr07h_folio = '#{params[:req_id]}'"
    @request['comments'] = []
    result = connection.exec_query(sql_comments)
    result.each do |row|

app/helpers/projects_helper.rb
module ProjectsHelper
end

app/views/projects/_header.html.erb
<h3 class="center project-title-header"> <%= link_to @project.internal_name, @project %></h3>
<!--
<div class="center project-participants">
  <img src="<%= @project.manager.picture %>" class="circle picture-48 responsive-img tooltipped" data-position="bottom" data-delay="50" data-tooltip="Responsable: <%= @project.manager.full_name %>">
  <img src="<%= @project.agent.picture %>" class="circle picture-48 responsive-img tooltipped" data-position="bottom" data-delay="50" data-tooltip="Agente: <%= @project.agent.full_name %>">
  <%= image_tag "dots.png", class: 'circle picture-48 responsive-img' %>
</div>
-->
<div class="spacer"></div>

<% if show_top_menu %>
<table id="project-menu">
<tr>
<td><a class="waves-effect waves-light menu-item red darken-1" href="<%= "#{project_url}" %>/detalles">Información</a></td>
<td><a class="waves-effect waves-light menu-item deep-orange lighten-1" href="<%= "#{project_url(@project)}" %>/presupuesto">Presupuesto</a></td>
<td><a class="waves-effect waves-light menu-item amber accent-4" href="<%= "#{project_url(@project)}" %>/mensajes">Mensajes</a></td>
<td><a class="waves-effect waves-light menu-item green" href="<%= "#{project_url(@project)}" %>/calendario">Calendario</a></td>
<td><a class="waves-effect waves-light menu-item cyan" href="<%= "#{project_url(@project)}" %>/servicios">Servicios</a></td>
<td><a class="waves-effect waves-light menu-item purple" href="<%= "#{project_url(@project)}" %>/personas">Personas</a></td>
<td><a class="waves-effect waves-light menu-item pink darken-3" href="<%= "#{project_url(@project)}" %>/documentos">Documentos</a></td>
</tr>
</table>
<% end %>

app/views/projects/_messages.html.erb
<div class="project-area-title">Mensajes</div>
<div class="project-area-actions"><a href="<%= "#{project_url}" %>/mensajes/nuevo" class="btn blue">Publicar un mensaje</a></div>

<table class="messages-list">
<% @project.messages.where(status: Message::ACTIVE).order('created_at DESC').each do |msg| %>
<tr>
  <td class="avatar-td"><img src="<%= msg.user.picture %>" class="circle responsive-img picture-48"></td>
  <td>
    <div class="message-meta"><%= msg.user.full_name %> • <%= f_date(msg.created_at) %></div>
    <div class="message-content"><a href="<%= "#{project_url}" %>/mensajes/<%= msg.id %>"><strong><%= msg.title %></strong> – <%= strip_tags(msg.content).truncate_words(40) %></a></div>
  </td>
</tr>
<% end %>
</table>

app/views/projects/_schedules_list.html.erb
<table class="schedules-list <%= table_class %>">
<% schedules_list.each do |sched| %>
<tr>
  <% if sched.start_date.strftime('%Y-%m-%d') == sched.end_date.strftime('%Y-%m-%d') %>
    <td class="calendar-td"></td>
    <td class="calendar-td">
  	  <div class="card calendar-card">
  	    <div class="month"><%= sched.start_date.strftime('%b') %></div>
  	    <div class="day"><%= sched.start_date.strftime('%d') %></div>
  	  </div>	  	
    </td>
    <td class="calendar-td"></td>
  <% else %>
    <td class="calendar-td">
      <div class="card calendar-card">
  	    <div class="month"><%= sched.start_date.strftime('%b') %></div>
  	    <div class="day"><%= sched.start_date.strftime('%d') %></div>
  	  </div>
    </td>
    <td class="calendar-td"><i class="material-icons grey-text">arrow_forward</i></td>
    <td class="calendar-td">
  	  <div class="card calendar-card">
  	    <div class="month"><%= sched.end_date.strftime('%b') %></div>
  	    <div class="day"><%= sched.end_date.strftime('%d') %></div>
  	  </div>	  	
    </td>
  <% end %>
  <td class="calendar-data">
    <div class="schedule-title"><a href="<%= "#{project_url}" %>/calendario/<%= sched.id %>"><strong><%= sched.title %></strong></a></div>
    <div class="schedule-meta">
      <% if !sched.all_day && sched.start_date.strftime('%Y-%m-%d') == sched.end_date.strftime('%Y-%m-%d') %>
        <%= f_date(sched.created_at) %>
         •
      <% end %>
      Creado por: <%= sched.user.full_name %>
    </div>
  </td>
</tr>
<% end %>
</table>

app/views/projects/details.html.erb
<%= render 'header', project: @project, show_top_menu: true %>
<div class="project-area z-depth-1" id="project-details">

<div class="row">
	<div class="col s9">

  <div class="row">
    <div class="col s12">
    <label>Nombre del proyecto</label>
    <strong><%= @project.internal_name %></strong>
    </div>
  </div>
  <div class="row">
  	<div class="col s12">
  		<label>Cliente</label>
  		<%= @project.client.real_name %>
    </div>
  </div>
  <div class="row">
  	<div class="col s3">
  	  <label>Tipo</label>
      <%= @project.project_type.name %>
    </div>
  	<div class="col s3">
  	  <label>Investigación</label>
      <%= @project.research_text %>
    </div>
    <div class="col s3">
  	  <label>Núm. NetMultix</label>
      <%= @project.erp_number %>
    </div>
    <div class="col s3">
  	  <label>Núm. Externo</label>
      <%= @project.number %>
    </div>
  </div>

  <div class="row">
  	<div class="col s12">
  		<label>Objetivo</label>
  		<%= @project.goal %>
    </div>
  </div>
  <div class="row">
  	<div class="col s12">
  		<label>Resultados Esperados</label>
  		<%= @project.results %>
    </div>
  </div>
  <div class="row">
  	<div class="col s6">
  		<label>Responsable técnico</label>
  		<table><tr><td style="width: 34px;"><img style="margin-top:4px;" src="<%= @project.manager.picture %>" class="circle picture-32 responsive-img"></td><td><%= @project.manager.full_name %></td></tr></table>
    </div>
    <div class="col s6">
  		<label>Ejecutivo del proyecto</label>
  		<table><tr><td style="width: 34px;"><img style="margin-top:4px;"  src="<%= @project.agent.picture %>" class="circle picture-32 responsive-img"></td><td><%= @project.agent.full_name %></td></tr></table>
    </div>
  </div>
  <div class="row">
  	 <div class="col s6">
  		<label>Departamento</label>
        <%= @project.department.name  %>
     </div>
     <div class="col s6">
     	<label>Ubicación</label>
        <%= @project.business_unit.name  %>
     </div>
   </div>

   <div class="fixed-action-btn horizontal">
    <a class="btn-floating btn-large red" href="<%= edit_project_path(@project) %>">
      <i class="large material-icons">mode_edit</i>
    </a>
  </div>
</div>
<div class="col s3">
	<div class="center-align">
	  <label>Estado actual</label>
	  <%= render 'status_line', project: @project %>
	  <div class="current-status-msg">
	    <%= @project.project_status.name rescue '--' %>
	  </div>
	  <a id="update-status-link" class="waves-effect waves-light btn right blue modal-trigger">Cambiar estado</a>
    </div>
</div>
</div>

    
 </div>


 <!-- Modal Status -->
<div id="modal-status" class="modal">
  <form action="<%= project_url %>/update-status" method="POST">
  <%= form_with(model: @project, local: true) do |form| %>
  <div class="modal-content">
  	<div class="row">
    <div class="input-field col s12">
      <%
      sel_options = ''
      ps = ProjectStatus.where(project_type_id: @project.project_type_id).order(:position)
      ps.each do |s|
        sel_options += "<option value=\"#{s.id}\">#{s.name}</option>"
      end %>
      <%= select_tag "new_status", sel_options.html_safe %>
      <label for="new_status">Nuevo estado</label>
    </div>
    <div class="input-field col s12">
      <%= text_area_tag "status_notes", nil, class: "materialize-textarea" %>
      <label for="status_notes">Notas</label>
    </div>
  </div> 
  <div class="modal-footer">
    <button type="submit" class="modal-action modal-close waves-effect red btn">Cambiar estado</button>
  </div>
  <% end %>
  </form>
</div>

app/views/projects/index.html.erb
<div class="project-area z-depth-1">
<div class="row">
  <div class="col s12">

    <a class='dropdown-button btn white black-text btn-flat' id='project-dropdown-title' href='#' data-activates='dropdown1'><%= @projects.count rescue '-' %> <%= Project::PROJECT_FILTER[@p] %> <i class="material-icons right black-text">arrow_drop_down</i></a>

    <ul id='dropdown1' class='dropdown-content'>
      <li><a href="?p=responsable">Proyectos en los que soy responsable</a></li>
      <li><a href="?p=participo">Proyectos en los que participo</a></li>
      <li><a href="?p=mis-proyectos">Todos mis proyectos</a></li>
      <% if current_user.is_agent? %>
        <li><a href="?p=administro">Proyectos que administro</a></li>
        <li><a href="?p=activos">Proyectos activos</a></li>
        <li><a href="?p=todos">Todos los proyectos</a></li>
      <% end %>
    </ul>
    <% if current_user.is_agent? %>
      <%= link_to 'Crear Nuevo Proyecto', new_project_path, class: 'waves-effect waves-light btn right blue' %>
    <% end %>
  </div>
</div>

<table id="project-list" class="responsive-table bordered">
  <thead>
    <tr>
      <th>Proyecto</th>
      <th>Fecha Termino</th>
      <th>Responsable</th>
      <th>Presupuesto</th>
      <th>Status</th>
      <th colspan="3"></th>
    </tr>
  </thead>

  <tbody>
    <% if @projects %>
      <% @projects.each do |project| %>
        <tr>
          <td>
            <%= link_to project.internal_name, project %>
            <div class="extra"><%= project.client.short_name %></div>
          </td>
          <td class="no-wrap">
            <%= project.end_date.strftime "%B %e, %Y" rescue '--' %>
            <div class="extra"><%= f_date_no_time(project.end_date) rescue '--' %></div>
          </td>
          <td class="no-wrap project-manager">
            <img src="<%= project.manager.picture %>" class="left circle">
            <%= project.manager.full_name %>
            <div class="extra">
              <%= project.department.name %>
            </div>
          </td>
          <td class="no-wrap project-budget">
            <% budget_resume = project.budget_resume %>
            <% if budget_resume['autorizado'] == 0 
                 budget_percentage = 100
               else
                 budget_percentage = 100 - (budget_resume['disponible'] * 100 / budget_resume['autorizado']).round 
               end
            %>
            <div class="c100 p<%= budget_percentage %> xsmall c-green">
              <span><%= budget_percentage %>%</span>
              <div class="slice">
                <div class="bar"></div>
                <div class="fill"></div>
              </div>
            </div>
            <%= number_to_currency(budget_resume['autorizado'], negative_format: '<span class="red-text">-%u%n</span>'.html_safe) %>
            <div class="extra">Disponible: <%= number_to_currency(budget_resume['disponible'], negative_format: '<span class="red-text">-%u%n</span>'.html_safe) %></div>
          </td>
          <td class="no-wrap"><%= project.project_status.name rescue '--' %></td>
        </tr>
      <% end %>
    <% end %>
  </tbody>
</table>
</div>

app/views/projects/people.html.erb
<%= render 'header', project: @project, show_top_menu: true %>
<div class="project-area z-depth-1">
  <div class="project-area-title">Personas</div>
  <div class="spacer-2em"></div>
  <table class="people-table bordered highlight">
    <tr>
      <td colspan="4"><h4>CIMAV</h4></td>
      <td colspan="2"><a class="waves-effect waves-light btn blue" id="add-participant-link">Agregar</a>
</td>
    </tr>
    <tr>
      <th></th>
      <th>Nombre</th>
      <th>Rol</th>
      <th>Correo</th>
      <th>Teléfono</th>
      <th></th>
    </tr>
    <!-- RESPONSABLE -->
    <tr>
      <td class="person-avatar"><img src="<%= @project.manager.picture %>" class="circle picture-64 responsive-img"></td>
      <td class="person-name"><%= @project.manager.full_name %></td>
      <td>Responsable Técnico</td>
      <td><%= @project.manager.email %></td>
      <td>Tel. <%= @project.manager.phone %></td>
      <td></td>
    </tr>
    <!-- AGENTE -->
    <tr>
      <td class="person-avatar"><img src="<%= @project.agent.picture %>" class="circle picture-64 responsive-img"></td>
      <td class="person-name"><%= @project.agent.full_name %></td>
      <td>Ejecutivo CIMAV</td>
      <td><%= @project.agent.email %></td>
      <td>Tel. <%= @project.agent.phone %></td>
      <td></td>
    </tr>
    <% @project.project_participants.each do |participant| %>
      <tr>
        <td class="person-avatar"><img src="<%= participant.user.picture %>" class="circle picture-64 responsive-img"></td>
        <td class="person-name"><%= participant.user.full_name %></td>
        <td><%= participant.role %></td>
        <td><%= participant.user.email %></td>
        <td>Tel. <%= participant.user.phone %></td>
        <td class="person-actions">
          <a class="participant-delete" data-turbolinks="false" data-project-id="<%= @project_id %>" data-project-participant-id="<%= participant.id %>"><i class="material-icons tiny grey-text">cancel</i></a>
        </td>
      </tr>
    <% end %>
  	<% @project.project_person.each do |project_person| %>
      <tr>
  	    <td class="person-avatar"><img src="<%= project_person.person.picture %>" class="circle picture-64 responsive-img"></td>
  	    <td>
  	      <div class="person-name"><%= project_person.person.name %></div>
  	      <div class="person-role"><%= project_person.person.attachable.short_name %></div>
  	    </td>
        <td><%= project_person.person.email %></td>
  	    <td>Tel. <%= project_person.person.phone %></td>
        <td class="person-actions">
          <a class="file-delete" data-turbolinks="false" data-project-id="<%= @project_id %>" data-project-person-id="<%= project_person.id %>"><i class="material-icons tiny grey-text">cancel</i></a>
        </td>
      </tr>
    <% end %>
  </table>
</div>

<!-- Modal New Participant -->
<div id="modal-new-participant" class="modal bottom-sheet">
  <div class="modal-content">
    <form action="<%= project_participants_path %>" method="POST">
    <% participant = ProjectParticipant.new %>
    <%= form_with(model: participant, local: true) do |form| %>
      <div class="row">
        <div class="col s5">
          <div class="field">
            <%= form.collection_select :user_id, User.where("id NOT IN (SELECT user_id FROM project_participants WHERE project_id = ?) AND id <> ? AND id <> ?", @project.id, @project.manager_id, @project.agent_id).order('first_name, last_name'), :id, :full_name  %>
          </div>
        </div>
        <div class="col s4">
          <div class="field">
            <input type="hidden" name="project_participant[project_id]" value="<%= @project.id %>">
            <%= form.text_field :role, id: :project_role, placeholder: "Rol...", class: "participant_role_input" %>
          </div>
        </div>
        <div class="col s3">
          <button id="new_folder_btn" type="submit" class="btn red" data-user-id="<%= current_user.id %>" data-project-id="<%= @project.id %>">Agregar participante</button>
        </div>
      </div>
    <% end %>
  </div>
</div>

<script>
Materialize.toast('<%= notice %>', 3000)
</script>